bug: need to account for poorly formatted pages
aceback (most recent call last):
  File "index.py", line 138, in <module>
    main()
  File "index.py", line 91, in main
    citySoup.find('span', {'class': 'latitude'}).contents[0]
  File "index.py", line 134, in coordinatesToRadians
    output = output + int(inputArgument[inputDelimiter2 + 1:-2]) / 1000
ValueError: invalid literal for int() with base 10: '49.62'