bug: need to check for presence of linked city
Traceback (most recent call last):
  File "index.py", line 80, in <module>
    main()
  File "index.py", line 66, in main
    citySuffix = link.contents[3].a.get('href')
AttributeError: 'NoneType' object has no attribute 'get'